spring.application.name=mcp-service
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090
spring.threads.virtual.enabled=true
spring.ai.mcp.server.protocol=streamable
server.port=8082
#debug=true