spring.application.name=mcp-client
server.port=8081

#export SPRING_AI_OPENAI_API_KEY=

##
## OAUTH
spring.security.oauth2.client.provider.spring.issuer-uri=http://localhost:9090
spring.security.oauth2.client.registration.spring.provider=spring
spring.security.oauth2.client.registration.spring.client-id=spring
spring.security.oauth2.client.registration.spring.client-secret=spring
spring.security.oauth2.client.registration.spring.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.spring.client-authentication-method=client_secret_basic
spring.security.oauth2.client.registration.spring.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.spring.scope=openid

#server.servlet.session.cookie.name=MCP_CLIENT_SESSION

##
## MCP
spring.ai.mcp.client.type=SYNC
spring.ai.mcp.client.initialized=false
spring.ai.mcp.client.streamable-http.connections.scheduler.url=http://localhost:8082


##
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework=DEBUG